global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
